### ISSUE TITLE
WARNING in entrypoint size limit,  Entrypoint undefined = index.html

### ISSUE THREAD

**Issue by darvesh** [esausilva/react-starter-boilerplate-hmr#1]
`yarn build
yarn run v1.3.2
$ rimraf dist
$ cross-env NODE_ENV=production webpack -p --env.env=prod
**(node:30669) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead**
**(node:30669) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly** instead
Hash: ef4be58bb97e7c02b221
Version: webpack 4.0.1
Time: 16326ms
Built at: 3/12/2018 10:56:18 PM
                                                 Asset       Size  Chunks                    Chunk Names
        static/DynamicPage.ef4be58bb97e7c02b221.js.map  810 bytes       1  [emitted]         DynamicPage
                static/NoMatch.ef4be58bb97e7c02b221.js  361 bytes       0  [emitted]         NoMatch
                    static/app.ef4be58bb97e7c02b221.js   56.8 KiB       2  [emitted]         app
                 static/vendor.ef4be58bb97e7c02b221.js    363 KiB       3  [emitted]  [big]  vendor
    styles/styles.d41d8cd98f00b204e9800998ecf8427e.css   71 bytes       3  [emitted]         vendor
    styles/styles.cc403e05dca835cff7c748e8c7fd6051.css  250 bytes       2  [emitted]         app
            static/NoMatch.ef4be58bb97e7c02b221.js.map  797 bytes       0  [emitted]         NoMatch
            static/DynamicPage.ef4be58bb97e7c02b221.js  377 bytes       1  [emitted]         DynamicPage
                static/app.ef4be58bb97e7c02b221.js.map    233 KiB       2  [emitted]         app
styles/styles.cc403e05dca835cff7c748e8c7fd6051.css.map  467 bytes       2  [emitted]         app
             static/vendor.ef4be58bb97e7c02b221.js.map   1.57 MiB       3  [emitted]         vendor
styles/styles.d41d8cd98f00b204e9800998ecf8427e.css.map  127 bytes       3  [emitted]         vendor
                                           favicon.ico   24.3 KiB          [emitted]         
                                            index.html  784 bytes          [emitted]         
Entrypoint app [big] = static/vendor.ef4be58bb97e7c02b221.js styles/styles.d41d8cd98f00b204e9800998ecf8427e.css static/vendor.ef4be58bb97e7c02b221.js.map styles/styles.d41d8cd98f00b204e9800998ecf8427e.css.map static/app.ef4be58bb97e7c02b221.js styles/styles.cc403e05dca835cff7c748e8c7fd6051.css static/app.ef4be58bb97e7c02b221.js.map styles/styles.cc403e05dca835cff7c748e8c7fd6051.css.map
  [13] ./node_modules/semantic-ui-react/dist/es/index.js + 223 modules 619 KiB {3} [built]
       |    224 modules
  [39] ./node_modules/react-router-dom/es/index.js + 30 modules 75.7 KiB {2} [built]
       |    31 modules
 [143] (webpack)/buildin/module.js 519 bytes {3} [built]
 [152] (webpack)/buildin/global.js 509 bytes {3} [built]
 [294] ./src/index.js + 5 modules 4.83 KiB {2} [built]
       | ./src/index.js 476 bytes [built]
       |     + 5 hidden modules
 [295] ./src/index.css 41 bytes {2} [built]
 [307] multi ./src/index.js 28 bytes {2} [built]
 [518] multi semantic-ui-react 28 bytes {3} [built]
    + 511 hidden modules

**WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.**
Assets: 
  static/vendor.ef4be58bb97e7c02b221.js (363 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (420 KiB)
      static/vendor.ef4be58bb97e7c02b221.js
      styles/styles.d41d8cd98f00b204e9800998ecf8427e.css
      static/app.ef4be58bb97e7c02b221.js
      styles/styles.cc403e05dca835cff7c748e8c7fd6051.css

Child html-webpack-plugin for "index.html":
     1 asset
    **Entrypoint undefined = index.html**
       [0] (webpack)/buildin/module.js 519 bytes {0} [built]
       [1] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] ./node_modules/html-webpack-plugin/lib/loader.js!./public/index.html 811 bytes {0} [built]
        + 1 hidden module
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--5-2!node_modules/postcss-loader/lib/index.js??ref--5-3!src/index.css:
    **Entrypoint undefined = extract-text-webpack-plugin-output-filename**
       [1] ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/lib??ref--5-3!./src/index.css 246 bytes {0} [built]
        + 1 hidden module
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--5-2!node_modules/postcss-loader/lib/index.js??ref--5-3!src/components/layout.css:
    **Entrypoint undefined = extract-text-webpack-plugin-output-filename**
       2 modules
Done in 23.66s.
`

**Comment by esausilva** [comment]
I just cloned the repo, installed dependencies and app ran successfully.

Two questions:

1. If you cloned the repo, What changes were made to the project?
2. If you were following the tutorial, At what point in the tutorial did you get this error?
