### ISSUE TITLE
To deploy on server

### ISSUE THREAD

**Issue by caseydev** [esausilva/react-starter-boilerplate-hmr#4]
Hi Mate,

I have been using this starter. Now i am going to host on my server. When i have build it will create file inside of Dist folder. But it will not open as normal so is there any idea , please can you help?

**Comment by esausilva** [comment]
Let's say you want to deploy to Heroku, you will need to create a Node server.

- First clone this repo: https://github.com/esausilva/quick-node-server
- Then create a `client` directory and copy everything from this template (_react-starter-boilerplate-hmr_) into the newly created `client` directory
- Open `package.json` from _quick-node-server_ and add the following scripts

```
"start:server" : "cd client && yarn build && cd .. && yarn start",
"start": "node server.js",
"heroku-postbuild": "cd client && npm install && npm install --only=dev --no-shrinkwrap && npm run build"
```

- Open `server.js` and replace `public` for `client/build`
- Follow the **Production Deployment** instruction from my other tutorial [here](https://medium.freecodecamp.org/how-to-make-create-react-app-work-with-a-node-backend-api-7c5c48acb1b0) (towards the end of the post)

And that should be it.

If this answers your question, please close the issue 🙂

**Comment by caseydev** [comment]
Thanks Mate. I was out so didn't tried yet so not closed. Anyway thanks for prompt response.

**Comment by esausilva** [comment]
No problem
