### ISSUE TITLE
script dev 

### ISSUE THREAD

**Issue by ohoroyoi** [esausilva/react-starter-boilerplate-hmr#5]
How about change like this,

> webpack-dev-server --env.env=dev --port 8080 --hot --host 0.0.0.0

it works my environment.

**Comment by esausilva** [comment]
Well, I have those setting in the Webpack configuration `webpack.dev.js` and I rather have them there, but is just my preference 🙂

```
const config = {
  ...
  devServer: {
    host: 'localhost',    // <-- here
    port: port,    // <-- here
    historyApiFallback: true,
    hot: true,    // <-- here
    open: true
  }
};
```
